/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.northeastern.cs5500.recipe.controller;

import static com.google.common.truth.Truth.assertThat;
import static com.google.common.truth.Truth.assertWithMessage;

import edu.northeastern.cs5500.recipe.model.Recipe;
import edu.northeastern.cs5500.recipe.repository.InMemoryRepository;
import org.junit.jupiter.api.Test;

class RecipeControllerTest {
    @Test
    void testRegisterCreatesRecipes() {
        RecipeController recipeController = new RecipeController(new InMemoryRepository<Recipe>());
        assertThat(recipeController.getRecipes()).isNotEmpty();
    }

    @Test
    void testRegisterCreatesValidRecipes() {
        RecipeController recipeController = new RecipeController(new InMemoryRepository<Recipe>());

        for (Recipe recipe : recipeController.getRecipes()) {
            assertWithMessage(recipe.getTitle()).that(recipe.isValid()).isTrue();
        }
    }

    @Test
    void testCanAddRecipe() {
        // This test should NOT call register
        // TODO: implement this test.
    }

    @Test
    void testCanReplaceRecipe() {
        // This test should NOT call register
        // TODO: implement this test.
    }

    @Test
    void testCanDeleteRecipe() {
        // This test should NOT call register
        // TODO: implement this test
    }
}
